python3.9 train_pretrain.py train \
	--dataroot ./datasets/Manifold40-MAPS-96-3/ \
	--batch_size 32 --n_classes 40 \
	--augment_scale --n_epoch 300 \
	--name "PTmanifoldBase_cos1_0.5_of_center" \
	--weight_decay 0.05 \
	--mask_ratio 0.5 \
	--channels 10 --patch_size 64 \
	--lr 1e-4 \
	--weight 0.5 \
	--depth 12 \
	--n_dropout 2 \
	--heads 12 \
	--lr_milestones "none" --optim "adamw" \
	--encoder_depth 12 \
	--decoder_depth 6 \
	--decoder_dim 512 \
	--decoder_num_heads 16 \
	--checkpoint "none" \
	--num_warmup_steps "2" \
	--dim 768
